version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend